antenna3x4-v2.0:
  n_epochs: 32
  n_envs: 5
  n_steps: 64
  batch_size: 256
  n_timesteps: !!float 1e6
  policy: 'MultiInputPolicy'
  gamma: 0.98
  normalize_advantage: True
  max_grad_norm: 1.0
  gae_lambda: 0.9
  learning_rate: 0.0004896659534073028
  ent_coef: 3.6261556576911286e-05
  vf_coef: 0.07573895782828786
  clip_range: 0.05
  policy_kwargs: "dict(
                           activation_fn=nn.ReLU,
                           net_arch=dict(pi=[32, 32], vf=[32, 32]),
                          ortho_init=False
                           )"

# Default configuration for other environments
default:
  n_epochs: 10
  n_envs: 1
  n_steps: 2048
  batch_size: 64
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  gamma: 0.99
  normalize_advantage: True
  max_grad_norm: 0.5
  gae_lambda: 0.95
  learning_rate: 0.0003
  ent_coef: 0.0
  vf_coef: 0.5
  clip_range: 0.2
  policy_kwargs: "dict(
                       activation_fn=nn.ReLU,
                       net_arch=dict(pi=[64, 64], vf=[64, 64])
                       )"
